# --- !Ups

CREATE TABLE EXPERIMENT_VIEW(
    ID IDENTITY NOT NULL,
    EXPERIMENT_ID BIGINT NOT NULL,
    VIEW VARCHAR(255),
    TITLE VARCHAR(255),
    FILE_NAME VARCHAR(255),
    CONTENT VARCHAR(2147483647),
    STYLE VARCHAR(2147483647)
);
CREATE INDEX IX_EXPERIMENT_VIEW_EXPERIMENTS ON EXPERIMENT_VIEW(EXPERIMENT_ID);
CREATE SEQUENCE EXPERIMENT_VIEW_SEQ;

CREATE TABLE EXPERIMENT_VIEW_SCRIPT(
    ID IDENTITY NOT NULL,
    EXPERIMENT_VIEW_ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    FILE_NAME VARCHAR(255),
    SCRIPT VARCHAR(2147483647)
);
CREATE INDEX IX_EXPERIMENT_VIEW_SCRIPT_EXPERIMENT_VIEW ON EXPERIMENT_VIEW_SCRIPT(EXPERIMENT_VIEW_ID);
CREATE SEQUENCE EXPERIMENT_VIEW_SCRIPT_SEQ;

CREATE TABLE EXPERIMENT_VIEW_TEMPLATE(
    ID IDENTITY NOT NULL,
    EXPERIMENT_VIEW_ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    FILE_NAME VARCHAR(255),
    CONTENT VARCHAR(2147483647)
);
CREATE INDEX IX_EXPERIMENT_VIEW_TEMPLATE_EXPERIMENT_VIEW ON EXPERIMENT_VIEW_TEMPLATE(EXPERIMENT_VIEW_ID);
CREATE SEQUENCE EXPERIMENT_VIEW_TEMPLATE_SEQ;

CREATE TABLE EXPERIMENT_VIEW_DEPENDENCY(
    ID IDENTITY NOT NULL,
    EXPERIMENT_VIEW_ID BIGINT NOT NULL,
    POSITION VARCHAR(255),
    CONTENT VARCHAR(2147483647)
);
CREATE INDEX IX_EXPERIMENT_VIEW_DEPENDENCY_EXPERIMENT_VIEW ON EXPERIMENT_VIEW_DEPENDENCY(EXPERIMENT_VIEW_ID);
CREATE SEQUENCE EXPERIMENT_VIEW_DEPENDENCY_SEQ;

ALTER TABLE EXPERIMENT_VIEW ADD CONSTRAINT FK_EXPERIMENTVIEW_EXPERIMENTS FOREIGN KEY(EXPERIMENT_ID) REFERENCES EXPERIMENTS(ID);
ALTER TABLE EXPERIMENT_VIEW_SCRIPT ADD CONSTRAINT FK_EXPERIMENTVIEWSCRIPT_EXPERIMENTVIEW FOREIGN KEY(EXPERIMENT_VIEW_ID) REFERENCES EXPERIMENT_VIEW(ID);
ALTER TABLE EXPERIMENT_VIEW_TEMPLATE ADD CONSTRAINT FK_EXPERIMENTVIEWTEMPLATE_EXPERIMENTVIEW FOREIGN KEY(EXPERIMENT_VIEW_ID) REFERENCES EXPERIMENT_VIEW(ID);
ALTER TABLE EXPERIMENT_VIEW_DEPENDENCY ADD CONSTRAINT FK_EXPERIMENTVIEWDEPENDENCY_EXPERIMENTVIEW FOREIGN KEY(EXPERIMENT_VIEW_ID) REFERENCES EXPERIMENT_VIEW(ID);

# --- !Downs

DROP TABLE EXPERIMENT_VIEW CASCADE;
DROP TABLE EXPERIMENT_VIEW_SCRIPT CASCADE;
DROP TABLE EXPERIMENT_VIEW_TEMPLATE CASCADE;
DROP TABLE EXPERIMENT_VIEW_DEPENDENCY CASCADE;

DROP SEQUENCE EXPERIMENT_VIEW_SEQ;
DROP SEQUENCE EXPERIMENT_VIEW_SCRIPT_SEQ;
DROP SEQUENCE EXPERIMENT_VIEW_TEMPLATE_SEQ;
DROP SEQUENCE EXPERIMENT_VIEW_DEPENDENCY_SEQ;

