# --- !Ups

CREATE TABLE EXPERIMENT_VIEW(
    ID IDENTITY NOT NULL,
    EXPERIMENT_ID BIGINT NOT NULL,
    VIEW VARCHAR(255),
    TITLE VARCHAR(255)
);
CREATE INDEX IX_EXPERIMENT_VIEW_EXPERIMENTS ON EXPERIMENT_VIEW(EXPERIMENT_ID);
CREATE SEQUENCE EXPERIMENT_VIEW_SEQ;

CREATE TABLE EXPERIMENT_VIEW_CONTENT(
    ID IDENTITY NOT NULL,
    NAME VARCHAR(255),
    FILE_NAME VARCHAR(255),
    TYPE VARCHAR(255),
    CONTENT VARCHAR(2147483647),
    LOAD_ORDER INTEGER,
    EXPERIMENT_VIEW_ID BIGINT NOT NULL
);
CREATE INDEX IX_EXPERIMENT_VIEW_CONTENT_EXPERIMENT_VIEW ON EXPERIMENT_VIEW_CONTENT(EXPERIMENT_VIEW_ID);
CREATE SEQUENCE EXPERIMENT_VIEW_CONTENT_SEQ;

ALTER TABLE EXPERIMENT_VIEW ADD CONSTRAINT FK_EXPERIMENTVIEW_EXPERIMENTS FOREIGN KEY(EXPERIMENT_ID) REFERENCES EXPERIMENTS(ID);
ALTER TABLE EXPERIMENT_VIEW_CONTENT ADD CONSTRAINT FK_EXPERIMENTVIEWCONTENT_EXPERIMENTVIEW FOREIGN KEY(EXPERIMENT_VIEW_ID) REFERENCES EXPERIMENT_VIEW(ID);

# --- !Downs

DROP TABLE EXPERIMENT_VIEW CASCADE;
DROP TABLE EXPERIMENT_VIEW_CONTENT CASCADE;

DROP SEQUENCE EXPERIMENT_VIEW_SEQ;
DROP SEQUENCE EXPERIMENT_VIEW_CONTENT_SEQ;
